export const FETCH_CITIES_START = 'FETCH_CITIES_START';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_ERROR = 'FETCH_CITIES_ERROR';

export const FETCH_CITY_START = 'FETCH_CITY_START';
export const FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS';
export const FETCH_CITY_ERROR = 'FETCH_CITY_ERROR';

export const FETCH_CITY_CATEGOTY_START = 'FETCH_CITY_CATEGOTY_START';
export const FETCH_CITY_CATEGORY_SUCCESS = 'FETCH_CITY_CATEGORY_SUCCESS';
export const FETCH_CITY_CATEGORY_ERROR = 'FETCH_CITY_CATEGORY_ERROR';